task 5 completed
Damz1/Be-NC-Project pull request #3
Opened 2023-03-28 15:44 UTC by Damz1

2023-03-28 15:56 UTC, alexdevdavis requested changes
A couple of changes to make before PR is approved, as per comments. 
Great progress today 👍

2023-03-28 15:56 UTC, alexdevdavis commented on __tests__/app.test.js
> +const { toBeSortedBy } = require("jest-sorted");
is this a VSCode auto-add that can be destroyed now?

2023-03-28 15:56 UTC, alexdevdavis commented on __tests__/app.test.js
> +        reviews.forEach((review) => {
need a length check before a forEach, lest you get false positives

2023-03-28 15:56 UTC, alexdevdavis commented on __tests__/app.test.js
> +          expect(review).toHaveProperty("comment_count");
test the expected data type of each property too

2023-03-28 15:56 UTC, alexdevdavis commented on package.json
>      "pg-format": "^1.0.4",
ensure that `pg-format` is in `dependencies`, not `devDependencies`, lest your app break on deploy, when dev dependencies get pruned

2023-03-28 19:05 UTC, merged

2023-03-29 07:35 UTC, Damz1 commented on __tests__/app.test.js
> +        reviews.forEach((review) => {
done, but not sure why, can't it fail otherwise?